[window]
opacity = 1
decorations = "None"
startup_mode = "Maximized"
title = ""
dynamic_title = false
decorations_theme_variant = "Dark"
padding = { x = 6 }
[mouse]
hide_when_typing = true
[font]
normal.family = "MesloLGLDZ Nerd Font Mono"
size = 12
offset.x=1
offset.y=15
