[window]
opacity = 0.9
decorations = "None"
startup_mode = "Fullscreen"
title = ""
dynamic_title = false
decorations_theme_variant = "Dark"
padding = { x = 5 }
[colors]
transparent_background_colors = true
[colors.normal]
black = '0x282828'
red = '0xcc241d'
green = '0x98971a'
yellow = '0xd79921'
blue = '0x458588'
magenta = '0xb16286'
cyan = '0x689d6a'
white = '0xa89984'
[colors.primary]
foreground = "0xebdbb2"
background = "0x1d2021"
[mouse]
hide_when_typing = true
[font]
normal.family = "JetBrainsMono Nerd Font"
size = 11
offset.x=1
offset.y=15
