return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "bash-language-server",
        "css-lsp",
        "eslint-lsp",
        "gopls",
        "helm-ls",
        "html-lsp",
        "json-lsp",
        "jdtls",
        "marksman",
        "phpactor",
        "typescript-language-server",
        "vue-language-server",
        "prettier",
        "prettierd",
        "clangd",
        "clang-format",
        "cpptools",
        "csharpier",
        "netcoredbg",
        "tailwindcss-language-server",
        "codelldb",
      },
    },
  },
}
